/*
 * Copyright (c) 2012-2014, Stuart Wheater, Newcastle upon Tyne, England. All rights reserved.
 */

// Device driver for BCM2835 - PWM

#include <Kernel/StdTypes.h>
#include <Kernel/Logging.h>
#include <Device/BCM2835_GPIO.h>
#include <Device/BCM2835_SystemTimer.h>
#include <Device/BCM2835_PWM.h>

#define PWN_BASE                  ((volatile UnsignedWord32*) 0x2020C000)
#define PWM_CONTROL_OFFSET        (0x00)
#define PWM_STATUS_OFFSET         (0x01)
#define PWM_DMA_CONFIG_OFFSET     (0x02)
#define PWM_CHANNEL1_RANGE_OFFSET (0x04)
#define PWM_CHANNEL1_DATA_OFFSET  (0x05)
#define PWM_FIFO_INPUT_OFFSET     (0x06)
#define PWM_CHANNEL2_RANGE_OFFSET (0x08)
#define PWM_CHANNEL2_DATA_OFFSET  (0x09)

#define PWM_CONTROL_CHANNEL1_ENABLE_MASK          (0x0001)
#define PWM_CONTROL_CHANNEL1_DISABLE_BIT          (0x0000)
#define PWM_CONTROL_CHANNEL1_ENABLE_BIT           (0x0001)
#define PWM_CONTROL_CHANNEL1_MODE_MASK            (0x0002)
#define PWM_CONTROL_CHANNEL1_MODE_PWM_BIT         (0x0000)
#define PWM_CONTROL_CHANNEL1_MODE_SERIALISER_BIT  (0x0002)
#define PWM_CONTROL_CHANNEL1_REPEAT_MASK          (0x0004)
#define PWM_CONTROL_CHANNEL1_REPEAT_DISABLE_BIT   (0x0000)
#define PWM_CONTROL_CHANNEL1_REPEAT_ENABLE_BIT    (0x0004)
#define PWM_CONTROL_CHANNEL1_SILENCE_MASK         (0x0008)
#define PWM_CONTROL_CHANNEL1_SILENCE_LOW_BIT      (0x0000)
#define PWM_CONTROL_CHANNEL1_SILENCE_HIGH_BIT     (0x0008)
#define PWM_CONTROL_CHANNEL1_POLARITY_MASK        (0x0010)
#define PWM_CONTROL_CHANNEL1_POLARITY_LOWHIGH_BIT (0x0000)
#define PWM_CONTROL_CHANNEL1_POLARITY_HIGHLOW_BIT (0x0010)
#define PWM_CONTROL_CHANNEL1_SOURCE_MASK          (0x0020)
#define PWM_CONTROL_CHANNEL1_SOURCE_DATA_BIT      (0x0000)
#define PWM_CONTROL_CHANNEL1_SOURCE_FIFO_BIT      (0x0020)
#define PWM_CONTROL_CHANNEL1_CLEAR_MASK           (0x0040)
#define PWM_CONTROL_CHANNEL1_CLEAR_NONE_BIT       (0x0000)
#define PWM_CONTROL_CHANNEL1_CLEAR_FIFO_BIT       (0x0040)
#define PWM_CONTROL_CHANNEL1_MSANABLE_MASK        (0x0080)
#define PWM_CONTROL_CHANNEL1_MSENABLE_PWM_BIT     (0x0000)
#define PWM_CONTROL_CHANNEL1_MSENABLE_MS_BIT      (0x0080)
#define PWM_CONTROL_CHANNEL2_ENABLE_MASK          (0x0100)
#define PWM_CONTROL_CHANNEL2_DISABLE_BIT          (0x0000)
#define PWM_CONTROL_CHANNEL2_ENABLE_BIT           (0x0100)
#define PWM_CONTROL_CHANNEL2_MODE_MASK            (0x0200)
#define PWM_CONTROL_CHANNEL2_MODE_PWM_BIT         (0x0000)
#define PWM_CONTROL_CHANNEL2_MODE_SERIALISER_BIT  (0x0200)
#define PWM_CONTROL_CHANNEL2_REPEAT_MASK          (0x0400)
#define PWM_CONTROL_CHANNEL2_REPEAT_DISABLE_BIT   (0x0000)
#define PWM_CONTROL_CHANNEL2_REPEAT_ENABLE_BIT    (0x0400)
#define PWM_CONTROL_CHANNEL2_SILENCE_MASK         (0x0800)
#define PWM_CONTROL_CHANNEL2_SILENCE_LOW_BIT      (0x0000)
#define PWM_CONTROL_CHANNEL2_SILENCE_HIGH_BIT     (0x0800)
#define PWM_CONTROL_CHANNEL2_POLARITY_MASK        (0x1000)
#define PWM_CONTROL_CHANNEL2_POLARITY_LOWHIGH_BIT (0x0000)
#define PWM_CONTROL_CHANNEL2_POLARITY_HIGHLOW_BIT (0x1000)
#define PWM_CONTROL_CHANNEL2_SOURCE_MASK          (0x2000)
#define PWM_CONTROL_CHANNEL2_SOURCE_DATA_BIT      (0x0000)
#define PWM_CONTROL_CHANNEL2_SOURCE_FIFO_BIT      (0x2000)
#define PWM_CONTROL_CHANNEL2_CLEAR_MASK           (0x4000)
#define PWM_CONTROL_CHANNEL2_CLEAR_NONE_BIT       (0x0000)
#define PWM_CONTROL_CHANNEL2_CLEAR_FIFO_BIT       (0x4000)
#define PWM_CONTROL_CHANNEL2_MSANABLE_MASK        (0x8000)
#define PWM_CONTROL_CHANNEL2_MSENABLE_PWM_BIT     (0x0000)
#define PWM_CONTROL_CHANNEL2_MSENABLE_MS_BIT      (0x8000)

#define PWM_CHANNEL1_GPIO       (18)
#define PWM_CHANNEL1_FUNCSELECT (GPIO_FUNCSELECT_ALTFUNC5)
#define PWM_CHANNEL2_GPIO       (19)
#define PWM_CHANNEL2_FUNCSELECT (GPIO_FUNCSELECT_ALTFUNC5)

//#define PWM_CHANNEL1_GPIO       (40)
//#define PWM_CHANNEL1_FUNCSELECT (GPIO_FUNCSELECT_ALTFUNC0)
//#define PWM_CHANNEL2_GPIO       (45)
//#define PWM_CHANNEL2_FUNCSELECT (GPIO_FUNCSELECT_ALTFUNC0)

void pwmInit(void)
{
    gpioFuncSelect(PWM_CHANNEL1_GPIO, PWM_CHANNEL1_FUNCSELECT);
    //    gpioSetPullControl(PWM_CHANNEL1_GPIO, GPIO_PULL_OFF);
    gpioFuncSelect(PWM_CHANNEL2_GPIO, PWM_CHANNEL2_FUNCSELECT);
    //    gpioSetPullControl(PWM_CHANNEL2_GPIO, GPIO_PULL_OFF);
    *(PWN_BASE + PWM_CONTROL_OFFSET) = 0x00AD;
}

void pwmSetRange(UnsignedByte channel, UnsignedWord32 range)
{
    *(PWN_BASE + PWM_CHANNEL1_RANGE_OFFSET) = range;
}

void pwmSetMark(UnsignedByte channel, UnsignedWord32 mark)
{
    *(PWN_BASE + PWM_FIFO_INPUT_OFFSET) = mark;
}

void pwmShutdown(void)
{
}
