#
# Copyright (c) 2012, Stuart Wheater, Newcastle upon Tyne, England. All rights reserved.
#

MAKE   = make
RM     = rm

all: all-arm

all-arm:
	$(MAKE) -C ARM all

clean:
	$(MAKE) -C ARM clean
	$(RM) -f *~ *.o
