#
# Copyright (c) 2012-2013, Stuart Wheater, Newcastle upon Tyne, England. All rights reserved.
#

MAKE = make
RM   = rm

all:
	$(MAKE) -C ARM all
	$(MAKE) -C ARMv6 all

clean:
	$(MAKE) -C ARM clean
	$(MAKE) -C ARMv6 clean
	$(RM) -f *~
